name: Diff CI

on:
  push:
    branches: [ main ]

jobs:
  diff-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute the diff
        run: |
            mkdir upstream && mkdir dev-pt
            git clone -b main https://github.com/cncf/glossary.git upstream
            git clone -b dev-pt https://github.com/cncf/glossary.git dev-pt
            echo "Updated files: "
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep differ | awk '/content/ {print $2}'
            echo "Files that exists only in main:"
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep "Only in upstream/content/en" | cut -d" " -f3-4
    
      - name: Setup input- update
        id: update
        run: echo "::set-output name=file_update::$(diff --brief -r upstream/content/en dev-pt/content/pt-br | grep differ | awk '/content/ {print $2}')"

      - name: Setup input - only
        id: new
        run: echo "::set-output name=file_only::$(diff --brief -r upstream/content/en dev-pt/content/pt-br | grep "Only in upstream/content/en" | cut -d" " -f3-4 > only-main-diff.md)"

      - name: Create the issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Diff files cncf/glossary to pt-br
          body: |
            Arquivos atualizados:
            ${{ steps.update.outputs.file_update }}

            Arquivos novos em main:
            ${{ steps.new.outputs.file_only }}
          labels: |
            weekly
            
