name: Check diff main/dev-pt

on:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  diff-issue:
    name: diff branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute the diff
        run: |
           ls -la
