name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute the diff
        run: |
            mkdir upstream && mkdir dev-pt
            git clone -b main git@github.com:cncf/glossary.git upstream
            git clone -b dev-pt git@github.com:cncf/glossary.git dev-pt
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep differ | awk '/content/ {print $2}'
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep "Only in upstream/content/en" | cut -d" " -f3-4
