name: Diff CI

on:
  push:
    branches: [ main ]

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Execute the diff
        run: |
            mkdir upstream && mkdir dev-pt
            git clone -b main https://github.com/cncf/glossary.git upstream
            git clone -b dev-pt https://github.com/cncf/glossary.git dev-pt
            echo "Updated files: "
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep differ | awk '/content/ {print $2}' > update-diff.md
            echo "Files that exists only in main:"
            diff --brief -r upstream/content/en dev-pt/content/pt-br | grep "Only in upstream/content/en" | cut -d" " -f3-4 > only-main-diff.md

      - name: Archive diff - update
        uses: actions/upload-artifact@v3
        with:
          name: diff-file-update
          path: update-diff.md
          
      - name: Archive diff - only
        uses: actions/upload-artifact@v3
        with:
          name: diff-file-only
          path: only-main-diff.md
    
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Diff files - main -> dev-pt
          body: |
                  This is a test
          labels: |
            test
